vm_types:
- name: container
  cloud_properties: {}

networks:
- name: redis-network #used for original redis deployment
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.11.0/28
    reserved:
    - 10.244.11.1

- name: redis
  type: manual
  subnets:
  - range: 10.244.13.0/24
    gateway: 10.244.13.1
    az: lite
    cloud_properties: {}

- name: redis-instances
  type: manual
  subnets:
  - range: 10.244.14.0/24
    gateway: 10.244.14.1
    az: lite
    cloud_properties: {}

disk_types:
- name: ten
  disk_size: 10_000
  cloud_properties: {}

azs:
- name: lite
  cloud_properties: {}

compilation:
  workers: 2
  reuse_compilation_vms: true
  network: redis
  az: lite
  cloud_properties: {}
