name: redis-broker
releases:
  - name: &broker-release on-demand-service-broker
    version: latest
  - name: &service-adapter-release redis-service-adapter
    version: latest
  - name: &redis-service-release redis
    version: latest

stemcells:
  - alias: trusty
    os: ubuntu-trusty
    version: latest

instance_groups:
  - name: broker
    instances: 1
    jobs:
      - name: broker
        release: *broker-release
        properties:
          port: 8080
          username: broker #or replace with your own
          password: password #or replace with your own
          disable_ssl_cert_verification: true
          bosh:
            url: https://192.168.50.4:25555
            authentication: # either basic or uaa, not both as shown
              basic:
                username: admin #or replace with your own
                password: admin #or replace with your own
          cf:
            url: https://api.local2.pcfdev.io
            authentication:
              url: https://uaa.local2.pcfdev.io
              user_credentials:
                username: admin
                password: admin
          service_adapter:
            path: /var/vcap/packages/odb-service-adapter/bin/service-adapter
          service_deployment:
            releases:
              - name: *redis-service-release
                version: latest
                jobs: [redis]
            stemcell:
              os: ubuntu-trusty
              version: latest
          service_catalog:
            id: redis-service-with-odb #create this yourself, can be human readable
            service_name: redis-service-with-odb
            service_description: Redis Service
            bindable: true
            plan_updatable: true
            tags: [redis]
            plans:
              - name: small
                plan_id: redis-service-with-odb-small # create this yourself, can be human readable
                description: A Redis deployment with a single instance of each job and persistent disk
                instance_groups:
                  - name: redis
                    vm_type: container
                    instances: 6
                    networks: [redis-instances] #from your cloud config
                    azs: [lite] #from your cloud config
                    persistent_disk_type: ten #from your cloud config
      - name: redis-service-adapter
        release: *service-adapter-release
    vm_type: container
    stemcell: trusty
    azs: [lite]
    networks:
      - name: redis #from your cloud config

  - name: register-broker
    lifecycle: errand
    instances: 1
    jobs:
      - name: register-broker
        release: *broker-release
        properties:
          broker_name: redis-service-with-odb
          disable_ssl_cert_verification: true
          cf:
            api_url: https://api.local2.pcfdev.io
            admin_username: admin
            admin_password: admin
    vm_type: container
    stemcell: trusty
    networks: [{name: redis}] #from your cloud config
    azs: [lite]

update:
  canaries: 1
  canary_watch_time: 3000-180000
  update_watch_time: 3000-180000
  max_in_flight: 4
